Update @expo/config-plugins to ^5.x
thebergamo/react-native-fbsdk-next pull request #327
Opened 2022-10-14 19:30 UTC by c-hristian

Update @expo/config-plugins to ^5.x to git rid of expo warnings for consuming apps

Test Plan: successful yarn install for both main repo and example repo. ran android example to ensure app was available and login functionality still persisted.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/108954694/195926861-9c1181f2-3141-423e-be4d-8b93b768bc74.png">

2022-10-14 20:43 UTC, jpalumickas commented
I also tested this in local, everything working fine.

2022-10-14 22:02 UTC, mikehardy approved these changes
This looks good to me, based entirely on the testing, really really appreciated.
I've been vocal on this repo and others that I cannot support Expo and we rely on community contributions, I will be equally vocal in saying that I will truly appreciate those contributions and will merge them and release them as quickly as possible if they come in.

Cheers

2022-10-15 03:45 UTC, mikehardy requested changes
This will likely be something subtle and only tangentially related, but CI needs to go green before I can merge it :weary:

2022-10-24 17:17 UTC, oliuradu commented
Any updates?

2022-10-24 18:16 UTC, mikehardy commented
@oliuradu it's open source: you see no updates, there are no updates. Feel free to take the PR, patch it up, and push it as a new PR if you need it. I'm happy to merge things when they appear to be working

2022-12-01 05:57 UTC, closed without merging