feat(expo): bump ios deployment target from 12.4 to 13
thebergamo/react-native-fbsdk-next pull request #344
Opened 2022-11-09 00:27 UTC by nkrekow

Bumped deployment target version from 12.4 to 13.0 to support Expo SDK 47

Overwhelming majority of iOS devices are on iOS 14 or 15 (see Apple's public usage data for reference) https://developer.apple.com/support/app-store/

Test Plan:

`yarn test`

2022-11-09 04:09 UTC, rgbutov commented
+++

2022-11-09 13:59 UTC, mikehardy requested changes
I don't think I can push a breaking change out to everyone just to support the next Expo version.
I understand the argument on distribution of users, but this is still a breaking change, and it is technically incorrect - this pod works fine with iOS 12. That's the actual minimum. 13 is wrong, it is not the minimum.

I haven't seen the requirement of bumping these in any of the other modules I maintain, why here?

You'll need to find another way to accomplish your goal, that does not require dropping support for users of this module that want to maintain iOS min version 12

Perhaps removing the platform lines entirely would work for you? The other modules I maintain do not seem to have them. Or replacing them with deployment_target so we may still specify the minimum 12 but it should work? https://guides.cocoapods.org/syntax/podspec.html#deployment_target

2022-11-09 15:04 UTC, LFMAKER commented
@mikehardy I also need this PR, I couldn't get it to work by overriding the pod's build_settings in the podfile. 
Could you help us with some workaround?

2022-11-09 15:18 UTC, mikehardy commented
@LFMAKER 

> Perhaps removing the platform lines entirely would work for you? The other modules I maintain do not seem to have them. Or replacing them with deployment_target so we may still specify the minimum 12 but it should work? https://guides.cocoapods.org/syntax/podspec.html#deployment_target

2022-11-09 15:19 UTC, mikehardy commented
To set very clear expectations: I do not use Expo, so this is not motivating for me to work on. Whoever *is* motivated will provide a PR that implements the needed changes, but it should not be a breaking change for all other consumers of the module

That disqualifies the current approach. I've left comments on a possible different approach. It is necessarily an exercise for motivated Expo users to implement, as they are affected

2022-11-10 19:01 UTC, MD555 commented
We are also running into this in our Expo project (bumping to SDK 47).  Perhaps @giautm can help take a look based on the original integration and offer in this comment?: https://github.com/thebergamo/react-native-fbsdk-next/pull/205#issuecomment-1048783693

2022-11-10 19:16 UTC, nkrekow commented
Temp work around for anyone trying to fix this - just update the values in the podspec files within your node_modules from 12.4 to 13 and then use the patch package to keep it that way

Re this being a breaking change: is this not the point of version numbers on packages? Also if you look at the stats linked above **99% of iOS users** are on iOS 15 or 14 (honestly probably higher than that now seeing as those stats are from May and iOS 16 has been released). 

By your own logic what about people who want their apps to support iOS 11? At what point would you feel comfortable dropping support for a version of iOS that less than 1% of users are on?

2022-11-10 19:23 UTC, mikehardy commented
@nkrekow the problem I have with just bumping the platform is that *it is technically incorrect*. You are arguing for a semver major based on a technically incorrect premise. facebook-ios-sdk supports iOS 11 so there is no reason we can't other than laziness in figuring out why it's a problem right now and solving that.

Evidence: I work on lots of modules. I work on one of the biggest modules in the react-native ecosystem, react-native-firebase. It supports Expo config plugins, and lots of people are using it. It also supports iOS 11. Which is old and obsolete and...*still works*. That starts off sounding like the "appeal to authority" cognitive bias but it isn't - it is actual experience maintaining an iOS11+ module where this isn't a problem. So, it's possible.

Thus, there's no reason to clip off support for the reason - as near as I can tell - that no one wants to figure out exactly why this module needs the platform minimum specified in some Expo-incompatible way whereas other modules I work on don't.

I want to fix the real technical problem instead of forcing (via this module along with all other lazy modules) another batch of devices into the landfill for no good technical reason.

This, to me, is still the important point to work on:

> Perhaps removing the platform lines entirely would work for you? The other modules I maintain do not seem to have them. Or replacing them with deployment_target so we may still specify the minimum 12 but it should work? https://guides.cocoapods.org/syntax/podspec.html#deployment_target

2022-11-10 19:25 UTC, nkrekow commented
Ahhh ok fair that makes sense thank ya for the more detailed explanation I
wasn't following at first :)

If I have time later today or tomorrow I'll look into doing via the
approach you outlined!

Thank ya for all your work here.


On Thu, Nov 10, 2022 at 11:23 AM, Mike Hardy ***@***.***>
wrote:

> @nkrekow <https://github.com/nkrekow> the problem I have with just
> bumping the platform is that *it is technically incorrect*. You are
> arguing for a semver major based on a technically incorrect premise.
> facebook-ios-sdk supports iOS 11 so there is no reason we can't other than
> laziness in figuring out why it's a problem right now and solving that.
>
> Evidence: I work on lots of modules. I work on one of the biggest modules
> in the react-native ecosystem, react-native-firebase. It supports Expo
> config plugins, and lots of people are using it. It also supports iOS 11.
> Which is old and obsolete and...*still works*. That starts off sounding
> like the "appeal to authority" cognitive bias but it isn't - it is actual
> experience maintaining an iOS11+ module where this isn't a problem. So,
> it's possible.
>
> Thus, there's no reason to clip off support for the reason - as near as I
> can tell - that no one wants to figure out exactly why this module needs
> the platform minimum specified in some Expo-incompatible way whereas other
> modules I work on don't.
>
> I want to fix the real technical problem instead of forcing (via this
> module along with all other lazy modules) another batch of devices into the
> landfill for no good technical reason.
>
> This, to me, is still the important point to work on:
>
> Perhaps removing the platform lines entirely would work for you? The other
> modules I maintain do not seem to have them. Or replacing them with
> deployment_target so we may still specify the minimum 12 but it should
> work? https://guides.cocoapods.org/syntax/podspec.html#deployment_target
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/thebergamo/react-native-fbsdk-next/pull/344#issuecomment-1310788756>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIM4AN6SRVL2VRBGZDLYXWTWHVDUFANCNFSM6AAAAAAR24MV5Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-10 19:26 UTC, mikehardy commented
Same patch-package workaround may be used to test my hypothesis that dropping platform lines or altering them to be deployment target lines in podspec. Hopefully they work, then we're all fixed up *and* support the actual lower bound of our wrapped SDK. I'm very curious to hear

2022-11-12 06:49 UTC, bradjones1 commented
So I ran into this today as well and wanted to share some findings. Also want to chime in here and say that I know how thankless open-source software maintainership can be, and I really appreciate the work @mikehardy has put into this conversation.

I _think_ this can be solved by bumping the `s.platforms` value in the expo adapter only.

I compared this package to another I use with a very similar profile - the Google native sign-in package. It has a lower platform value in the top-level podspec file than the Expo adapter.

https://github.com/react-native-google-signin/google-signin/blob/a18df090e1205ba161b4ac1f3b9b4f4bd498b665/RNGoogleSignin.podspec#L13

https://github.com/react-native-google-signin/google-signin/blob/a18df090e1205ba161b4ac1f3b9b4f4bd498b665/ios/ExpoAdapterGoogleSignIn.podspec#L13

Now I will fully admit that I am far from a Swift developer, but I think if the concern here is the compatibility profile of the package overall vs. the Expo integration, I think something similar could be done here? In my initial testing with a patched package, I am successfully building so I think this would work.

2022-11-12 11:40 UTC, mikehardy commented
We had a testable hypothesis above that would be non breaking for everyone, and you are proposing something that reduces the population that breaks but is still breaking and is still technically incorrect. Of course that will build, but how did it go when you tested the non breaking idea?

2022-11-12 11:45 UTC, mikehardy commented
I just re-read the docs, I can't see why someone doesn't test removing platform and using deployment target. Seems so simple, and actually correct, I honestly find it a little bizarre at this point

https://guides.cocoapods.org/syntax/podspec.html#platform
https://guides.cocoapods.org/syntax/podspec.html#deployment_target

It's important to note that the maintainer of google-signin is specifically maintaining it with a very light touch because yes, deciding to maintain an open source project is an otherwise thankless time sink and I imagine they have better things to do: https://github.com/react-native-google-signin/google-signin/issues/942

...so using them as a comparison is perhaps good as a demonstration of what can work but is only the logical fallacy of "appeal to authority" on a false authority as a demonstration of what *should* be done. I don't think the change was really examined there, it was simply merged. To be clear: I use google-signin myself and like the package and the maintainer, just saying "let's do it like google-signin does it" is not a technical argument.

2022-11-12 15:12 UTC, ericklombardo commented
I was doing some testing just patching the file **ios/ExpoAdapterFBSDKNext.podspec**

These are the result for my testing:

When a replace `s.platform = :ios, '12.0'` with `s.ios.deployment_target = '12.0'` i got the following error:

```
  (node_modules/react-native-fbsdk-next/ios/ExpoAdapterFBSDKNext/FacebookAppDelegate.swift:1:8)
    import ExpoModulesCore
      ^ compiling for iOS 12.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.0: /Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

Where i remove the line `s.platform = :ios, '12.0'`   i got the following error:

```
  (node_modules/react-native-fbsdk-next/ios/ExpoAdapterFBSDKNext/FacebookAppDelegate.swift:1:8)
    import ExpoModulesCore
      ^ compiling for iOS 11.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.0: /Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

The only solution that works for me is replacing this  `s.platform = :ios, '12.0'` with `s.platform = :ios, '13.0'`

2022-11-12 15:46 UTC, mikehardy commented
@ericklombardo thanks for running the test, I really appreciate that - now we have actual results.

I have to admit the results surprise me! I'm surprised that one module's minimum doesn't just override another module's minimum but actually errors, but :shrug: 

Okay: proposed solution in comments above of bumping the Expo Adapters minimum to 13 works for me I guess. :wave: to all those iOS 12 devices that still work just fine but aren't cool anymore

Action: someone post a PR that bumps expo adapter podspec to 13 and we're set I suppose

2022-11-12 16:12 UTC, ericklombardo commented
@mikehardy, I posted a PR with the change

2022-11-12 18:32 UTC, mikehardy commented
Fantastic - #352 supercedes this now. Still can't believe this is the correct course but that is surprise talking, experiments + evidence lead us where they will

2022-11-12 18:32 UTC, closed without merging