fix - expo plugin - update scheme injection
thebergamo/react-native-fbsdk-next pull request #504
Opened 2024-03-13 23:11 UTC by andrejpavlovic

Currently expo plugin injects scheme into all intent filters causing auto verify to break for deep links. See #329 issue for more info.

The fix is to follow latest instructions for configuring [Facebook Login for Android](https://developers.facebook.com/docs/facebook-login/android/#manifest) essentially removing existing injection of scheme into intent filters and adding `<activity android:name="com.facebook.FacebookActivity" .. />`

Test Plan:
Updated unit test to check that new `<activity android:name="com.facebook.FacebookActivity" .. />` has been added to the manifest.

Fixes #329

What this really does is remove support for Android WebViews as per [Deprecating Facebook Login support on Android WebViews](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews) which should be fine since we are well beyond Facebook SDK 8.2.0 at this point.

2024-03-14 17:39 UTC, JuanRdBO commented
> I haven't tested this with a fresh expo project and I'm not sure if custom tabs need extra configuration as per https://developer.chrome.com/docs/android/custom-tabs/guide-get-started . It's working for me in an existing project just fine though.

works for me too

2024-03-17 02:05 UTC, andrejpavlovic commented
I tried it with a new app and it's working fine there as well - so it should be fine to merge this at some point.

2024-04-10 19:43 UTC, mikehardy commented
Hey @andrejpavlovic 👋  - thanks for your patience

This looks close to working but I was unable to push to your branch (looks like you didn't grant maintainers rights to push?) so I can't fix the trivial problems

Two things:
- you need to either rebase upstream/master into your PR and repush it or merge upstream/master in to get CI changes which will clear the iOS build issue
- you need to run `yarn validate:prettier:fix` and commit the result for it to pass formatting checks

With those two items done it should clear CI then I can merge this - both are trivial / mechanical - the PR itself looks fine and since I don't use Expo myself I'll trust you - if you test it and it works, that works for me

Thanks!

2024-04-10 19:44 UTC, mikehardy requested changes
almost good to go - just needs changes as described

2024-04-10 20:18 UTC, closed without merging